# FROM ubuntu
# MAINTAINER karin schwartz <skarin4@gmail.com>
# RUN apt-get update -y && \ apt-get install -y python3-pip python3-dev
# COPY ./requirements.txt /home/juli/flask-docker/requirements.txt
# WORKDIR /app
# RUN pip install -r requirements.txt
# COPY . /home/juli/flask-docker
# ENTRYPOINT [ "python" ]
# CMD [ "flask3.py" ]

FROM ubuntu
WORKDIR /app
COPY flask3.py .
RUN apt update
RUN apt install -y python3
RUN apt install -y python3-pip
RUN pip3 install flask
EXPOSE 5000
CMD  FLASK_APP=/app/app.py flask run --host=0.0.0.0
